### ISSUE TITLE
Stereo? 

### ISSUE THREAD

**Issue by antithing** [terzakig/gptam#1]
Hi, thanks for making this code available. I have my own gpu based stereo feature detection and matching that I am trying to extend to mapping. 
How much work would it be for me to swap in a new detection /matching code into your code? 
While extending to stereo? 

It uses cv standards, so finds stereo keypoints, matches and triangulates. 

Thanks again!

**Comment by terzakig** [comment]
Hello,

Nice to hear you are considering using the code!

I would say that there are many ways to incorporate stereo into the tracking-and-mapping pipeline. Regardless, you would have to "operate" on the code, but to a very reasonable extent I think.

PTAM uses the tracker (tracker.cpp) to detect and track features from one (key)frame to the other. This is probably the most successful pipeline I have known and there is really no reason to change it, unless you want to make improvements in the way key-frames are chosen or key-points are detected, etc. 

So, what I would do is simply let PTAM choose the features and then run your stereo matcher to obtain depth estimates in every new keyframe on these particular features. The depth estimates would allow you to run a more robust relative pose estimate instead of the original method CalPoseUpdate(). Your relative pose estimate now, not only becomes more accurate, but will also be scale aware! 

Furthermore, you can update the map prior to the regular bundle adjustment (initiated every once in a while by the map-maker)  with more reliable depth estimates.

Of course, there are many details on how to incorporate the above, but do it one step at a time. First, make the trivial modifications so that you capture from two cameras. Then, focus on replacing/re-writing the method that does the pose prediction, aka "CalcposeUpdate()" using stereo pairs, i.e., one pair for the previous key-frame(s) and one pair for the predicted one(s). Note that you should do the same thing for initialization, MapMake::InitFromStereo(). Replace the homography-based method with your stereo matcher and make sure the map is initialized with this reconstruction, so that you can ensure it has proper scale from the beginning.  Of course, as before, don't bother to detect the features yourself. Let PTAM sort them out and  track them to the new key-frame. Then simply pass the coordinates to your stereo matcher in order to get the triangulation in each stereo rig. From there on, you should be able to work-out absolute relative pose.

This is a rather conceptual description and merely a suggestion on how to do it, but feel free to ask more specific questions once in the process of changing the code.
