### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by edgar-explorer** [terzakig/gptam#12]
I am sorry to disturb you. I encounter an error when make this code.
[  1%] Building CXX object CMakeFiles/gptam.dir/main.cpp.o
In file included from /home/chenchang1/code/gptam/Persistence/default.h:9:0,
                 from /home/chenchang1/code/gptam/Persistence/PVars.h:12,
                 from /home/chenchang1/code/gptam/Persistence/GUI.h:5,
                 from /home/chenchang1/code/gptam/Persistence/instances.h:1,
                 from /home/chenchang1/code/gptam/main.cpp:11:
/home/chenchang1/code/gptam/Persistence/../OpenCV.h:4:10: fatal error: cv.hpp: No such file or directory
 #include <cv.hpp>
          ^~~~~~~~
compilation terminated.
CMakeFiles/gptam.dir/build.make:62: recipe for target 'CMakeFiles/gptam.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/gptam.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gptam.dir/all' failed
make[1]: *** [CMakeFiles/gptam.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
sincerely

**Comment by terzakig** [comment]
Hi, happy you are interested in this piece of work.

It seems that cv.hpp is not reachable. There are 3 possible explanations:

a) OpenCV is not installed,

b) Your OpenCV installation is not in /usr/local/include (I have fixed this directory in the CMakeLists.txtx file because it almost always the path to OpenCV's .so and .h files and that is why the header file cannot be found.

b) At the time I wrote this code, I used OpenCV 3.4.2 (or slightly earlier than that) and I know it worked with many later versions. But there is a chance that your OpenCV is a very recent one (e.g. OpenCV4.1).

In any case, you can modify the paths directly inside the CMakeLists.txt file. If you have OpenCV installed, what version is it?
________________________________

**Comment by edgar-explorer** [comment]
Thank you for your response, I checked opencv path and changed in CMakeLists.txt. I installed ros-kinetic-opencv before, so the path was not /usr/local/include. Thank you, sincerely. In addition, have you make other contribution about this project, such as fusing camera with IMU?

**Comment by terzakig** [comment]
No problem, glad to help.

Adding an IMU would make SLAM much more realiable in PTAM, but I haven't had the opportunity to get my hands on an IMU with/without a camera, plus it will take several days of work. Perhaps in the future if I find a bit of time ( and an IMU).
________________________________

**Comment by edgar-explorer** [comment]
@terzakig   Have you published papers or released other code  about this work?

**Comment by terzakig** [comment]
Unfortunately not. The reason I did not make  a paper is that it looks very much like the original PTAM and I did not want the reviewers to think that I am trying to take credit of somebody else's work. I could change the interface and then it would be a brand new SLAM application, but I ran out of time and money. Another way of publishing this work was  to write a detailed manual explaining all algorithms and code in the visual SLAM pipeline used by PTAM (i.e., select and track keyframes, local adjustment, keyframe-based re-localization and background bundle adjustment), then publish it in the form of a peer-reviewed book or something of the sort, but would really need time (more than two months) which I did not have, so I left it at that.

On the other hand, there's a lot of work in it and if someone wants to cite it, I encourage them to use the repository url.
________________________________
