### ISSUE TITLE
failed to run gcalibrator

### ISSUE THREAD

**Issue by dorc23** [terzakig/gptam#14]
hi , 
after i change Videosource to get prerecorded video 
when i try to run the gcalibrator i get this error : 
any idea ??

![image](https://user-images.githubusercontent.com/35142668/70852282-4ccc0700-1ea8-11ea-91d8-db7c986ec07b.png)

**Comment by terzakig** [comment]
Hi,

It seems that there is an exception occurring while opening the calibrator window (see /GCVD/Window.cpp by searching "CreationError" in the code). I cannot be sure, but my first thought is that because the interface uses Xlib and maybe that's where your problem possibly lies. Does the PTAM window opens OK? I suspect not, in which case the reason must be related to a change in your system.
________________________________
