### ISSUE TITLE
to get projection of any keyframe , what i needs to do ?

### ISSUE THREAD

**Issue by dorc23** [terzakig/gptam#17]
hi 
The projection matrix is implicitly inferred by the intrinsics (K) , R and t for every keyframe, so you will not find it. You can easily compute it as follows;

P = K*[R | t]

But note that to use this matrix directly on a point in the world you must remove radial distortion at the Euclidean plane of projection before projecting onto the the images. To ue the projection matrix, you need to ensure that the images you are working on are devoid of radial distortion. Removing radial distortion on the entire image in sparse visual SLAM is an expensive operation and is not necessary. Thus, projection is modeled as follows:

    Project world point Pw to Camera frame point Pc:
    Pc = R*Pw + t

    Get the acual Euclidean projection m_u (u stands for 'u'ndistorted):
    m_u = Pc / Pc(3)

    Undistort the Euclidean projection m_u into m_d (d stands for 'd'istorted) using the ATAN2 model:
    mu = Distort(md) // note: Distort() is a non-linear operation that cannot be represented with up-to-scale matrix multiplications

    Finally, project to Image:
    m_i = K * m_d

this is your answer to get projection matrix for each keyframe.
P = K*[R | t] - i have the R and t in keyframe info but how i can get K matrix of each keyframe?

**Comment by terzakig** [comment]
The matrix K contains the intrinsic camera parameters:
K = [ fx,  0,  cx; 
         0,  fy, cy;
         0,   0,  1]

**Comment by dorc23** [comment]
yeah i know , but for each keyframe need to be different K matrix no? 
how i compute it during the process, save K matrix for each keyframe ?

**Comment by terzakig** [comment]
The K matrix is **the same** for each keyframe as I explained in an earlier message. The is simply because all keyframes are obviously captured by the same camera and therefore there is no need to do this on a keframe basis, unless, for some extreme reason, the physical properties of the camera change through time (for instance, if you are switching medium in which the SLAM takes place and/or some kind of auto-calibration takes place periodically), but there is no such thing happening here. So, to recapitulate, you can safely store the same K per keyframe entry.

**Comment by dorc23** [comment]
i understand now , thank you very much for your help !!
