### ISSUE TITLE
Undistort input image

### ISSUE THREAD

**Issue by jinchenglee** [terzakig/gptam#2]
Hi, thanks for the thorough "re-comment", which helps a lot in understanding the PTAM paper. 

One question regards to PatchFinder.cpp, comments around line 67 shows:
"  // To do this, we have to project the BATSIGNAL using the camera object. Problem is, the projection model is no longer linear,
  // due to the presence of the radial distortion compensation term. So what do we do???? Of copurse we linearize (hey, its 
  // practically a linear relationship for the most part anyway)..."

If I use an undistort image directly, then the intrinsic matrix alone will be linear, then the A warp matrix will be much easier to get since the T={R, t} is known/estimated in advance. I wonder why the author didn't choose this much easier way?

**Comment by terzakig** [comment]
Hello JC,


Wow! I am happy somebody actually reads the comments! And I am more happy that they can actually be helpful in understanding the details of PTAM implementation.


Let me re-state your question in my words, just to make sure I understood it correctly:


You are referring to a function in the patchfinder which partly does the so-called "epipolar search" that the paper talks about without expounding the concept too much though.

You are asking why not remove radial distortion DIRECTLY on the image and then use the STANDARD pinhole model, without the extra term that does radial distortion?


My answer is YES, it can be done, but then you will have to use a different radial distortion model, such as the one used by OpenCV for example. In this case, everything will be somewhat simpler, since the distortion term will not be part of the projection model; but also in this case, you will have to modify the ATANCamera class and this will have a cascading effect (code-wise) in many parts of PTAM, including the calibrator.


The distortion model that Klein used is from a Devernay and Faugeras paper (found here : https://hal.inria.fr/inria-00267247/document) which I am sure, you probably went though already. Under this model, unlike most methods for radial distortion removal that we know of, the distortion is presumably in Euclidean space. In other words, the normalized Euclidean projections of the points (and NOT the actual image locations) are distorted. Thus, although the projection on the image is standard pinhole, the atan2 distortion model is applied on to the Euclidean projection plane and this is why you cannot get rid of the distortion term.


Now, I was going to add support for non-atan cameras (wrote it in the README), which generally assume that radial distortion is an image-space issue rather than Euclidean-space problem, but I really ran out of time and mostly, money (I was a postdoc when I did this work). I also wanted to document every detail in the code so that people could actually reproduce it from scratch, but once again, my problem was university money :(, so I didn't do it. The comments explain a lot of things and if you are a somewhat advanced vision guy, you can actually pick-up and do your own hacking.


So, if you wish to use a different distortion model, I 'd more than happy to help you do it. You will definitely have to create a new camepe thera class and use in lieu of the ATANCamera throughout the entire code. It is not a super-difficult task, but you need to provide the same functionality that the ATAN2Camera class provides, primarily the derivatives of the entore projection, including the radial distortion coefficients.


Hope the above is helpful. Don't hesitate to contact me for anything else you need help or additional info!


Best


George

Straight lines have to be straight: automatic calibration ...<https://hal.inria.fr/inria-00267247/document>
hal.inria.fr
Machine Vision and Applications manuscript No. (will be inserted by the editor) Straight Lines Have to Be Straight Automatic Calibration and Removal of Distortion ...



________________________________

**Comment by jinchenglee** [comment]
Thanks for the thorough explanation. I understand the case now, but still feel confused why the PTAM authors choose this Euclidean-space distortion model other than the other one, between which the latter can shield the non-linear part from linear transforms and make a lot of other things simpler. 

I would like to help creating another camera class, but my problem is time, :P I am a full-time employee in the CV domain and SLAM is my part-time hobby only. 

I have registered cs231a at Stanford in coming Jan. that I can talk to professor whether this suites a good capstone project for the course. If that works and time allows, I'll contact you. 

Thanks again for your great work.

**Comment by terzakig** [comment]
Hi JC,


Glad to be of help.


Just a comment on your last query: The reason Klein & Murray chose to use Devernay ATAN2 model is because it was at the time a good model (and still is) for cheap lenses. A lot of cheap yet good quality off-the-shelf cameras can be modeled with some sort of  fish-eye geometry. However, this fact is not the actual reason for introducing the radial distortion into the projection function.


It is generally good practice to include the distortion model in the projection function (it is one of those things you only see in implementations but are skipped in the books). So, if the ideal  pinhole projection onto the image is p = K*m (where m is a normalized Euclidean coordinate vector and K are the camera intrinsics) then the model that accounts for the atan2 model is: p = K*f(m) where f is the Devernay distortion function. In the case of radial distortion modeled directly on the image, you would have something like, p = f( K*m ) where f is probably a polynomial distortion function.


Now, it all depends on how you want to cast you cost function for the problem at hand. The correct way is to use the derivatives of the distortion model, but you could also ignore it and use the undistorted coordinates (whether image location or normalized Euclidean). This choice heavily depends on a) How much radial distortion your lens actually has (some actually have none) and most importantly, b) How good your model is.


So, if you ask me, in any case, it is good practice to include the distortion model in the projection. In the special case of function "CalcSearchLevelAndWarpMatrix()" we are trying to back project into the real-world the coordinates of  a point +1 pixel to the left and +1 pixel downwards with repsect to an image feature location . To do so, we need to back-project first into the Euclidean image plane, which is by assumption, radially distorted and this is why linearization is necessary. We can actually skip this step, but the back-projection will not be probably less accurate.


Now let's think about this problem with a standard polynomial model on the image locations. You can assume that your image is already free from radial distortion (i.e. you have pre-procesed it) and there is no reason for linearization. However, when you are searching for a feature match on the image, it is preferable to work on actual coordinates rather than undistorted ones, because you can incorporate the derivatives of the distortion model in the Jacobian of your iterative procedure (typically such search algorithms are Gauss-Newton iterations). So, in practice, with a standard on-image distortion model you will avoid linearizations in CalcSearchLevelAndWarpMatrix(), but not in all remaining search/reprojection refinement routines, bundle adjustment included.


Conclusion: The PTAM practice is the one to follow regardless of distortion model. You need to have a camera class/entity which incorporates the overall projection pipeline, including the Jacobians more-less in the style it is done here. Decoupling radial distortion and the projection model is not necessarily a good practice.


Always happy to help/talk about this work. Thanks for your good words!


All the best


George

________________________________
