### ISSUE TITLE
Terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by SowmyaN9** [terzakig/gptam#4]
Hi terzakig,
While trying to execute gptam I encountered the above error. I understand that it's a memory allocation related error.I am using -std=c++11 instead of -std=c++14  and commented line " /usr/local/lib/libopencv_videoio.so " (could  not find this library,using opencv 2.4.8)in the CMakeLists.txt and on ubuntu 14.04. e The error got traced till line 73 in EssentialInit.cpp using gdb.
Can you please provide some insight to solve this issue?

**Comment by terzakig** [comment]
Hi,

Thanks for the feedback.

From what you are saying, the "bad_alloc"  error occurs probably inside the function that finds the function BestEssentialFromMatches_MLESAC() which is the one that runs RANSAC with the Torr-Zissermann robust error. I have tested the code and know that worked on a parallel project to PTAM, but I haven't been able to fully verify if this addition works with this code. I know it should, but consider it a "beta" version until verification.

On the other hand, with the new SLAM initialization code I am almost certain that you need the C++14 flag. Is there any particular reason to change it to C++11? I should also note that I made modifications to the CMakeLists.txt to accommodate OpenCV 3.4.1, but your modification probably solved this.  All in all, I would suggest using the  C++14 version to see if things return to normal. The reason I am saying this is because I don't make any use of dynamically allocated memory (it has been a while since I wrote this code but I am fairly positive) directly and therefore the standard library memory management fails somewhere. 

If you problem persists, I will try to reproduce the error; in the meanwhile, you can revert to the immediately previous version by checking-out to your local repository state to just before the commit titled "Multiple Initialization; ..." ( i.e., set your head to 9e12e2efc9a6b5ca70998d7f2072cf6b7d60b57d ). That should take you back to the version that uses homography-based SLAM initialization (which was tested using OpenCV 2.4.8 if I am not mistaken).

**Comment by SowmyaN9** [comment]
Thank you so much!! Yes standard library is throwing this error! I will try both the solutions.

**Comment by SowmyaN9** [comment]
Hi terzakig,
Thanks!! The above error is gone once head version is changed. I get this message when the code is executed :   Could not init from stereo pair, try again.
Waiting for mapmaker to reset ...DEBUG: Ditched 
0 trashed map points! I hope...
  Could not init from stereo pair, try again.
Is this related to camera settings in cfg file or the method of moving the camera to stereo initialize ? 
(I moved the webcam sideways). Can you please with the inistialisation ?

**Comment by terzakig** [comment]
Hi,

It seems that your visual SLAM initialization fails. My best guess is that you haven't calibrated your camera. You will have to calibrate the camera by running gcalibrator. After you have saved the calibration, you should have a new file called "camera.cfg". Rename it to "settings.cfg" and run gptam again, Now visual SLAM should be able to initialize.

**Comment by SowmyaN9** [comment]
Thanks again!! it's working for me!
