### ISSUE TITLE
What license is this software on?

### ISSUE THREAD

**Issue by DaviesX** [terzakig/gptam#5]

**Comment by terzakig** [comment]
Hi Chifeng,


It's freely available for any use as far as I am concerned. Now, since the code is (loosely)based on the original PTAM which is on a GPL licence, I just added a comment at the beginning of pertinent source files just to be on the safe side (for instance, the interface is still OpenGL based and the code is very close - but not same -  to the original).


But it really is a new project through and through, so my only requirement is to cite the repository in the comments, just to get the credit for this work as I never published anything out of it. Other than that you are free to do whatever you wish with it,



________________________________

**Comment by DaviesX** [comment]
Thanks @terzakig
